# Add source files here
#EXECUTABLE	:= vectorReduce
EXECUTABLE	:= vectorReduce
# Cuda source files (compiled with cudacc)
#CUFILES		:= vectorReduce.cu
CUFILES_sm_20		:= vectorReduce.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= \

################################################################################
# Rules and targets

include ../../common/common.mk
