#!/bin/sh
#####################################################################
# go.sh
# Generated by bench-run.pl
# /home/students/raya4213/benchmarks/bin/bench-run.pl --bench spec-cpu2006:int:473.astar:train --build base --prefix pin -t  /home/students/raya4213/checkpoints/checkPoint1A2Bit/obj-intel64/checkpoint1A2Bit.so -o astar.out -l 10000000000 -- --copy astar.out --log LOG
#####################################################################

#####################################################################
# Creating logfile
date >> LOG
#####################################################################

#####################################################################
# benchmark: spec-cpu2006/int/473.astar input: train 0
#####################################################################
# log file update
echo -n "Started : spec-cpu2006/int/473.astar input: train 0 at " >> LOG 
date >> LOG
# setup
ln -s /home/students/raya4213/benchmarks/src/spec-cpu2006/int/473.astar/builds/base/473.astar /home/students/raya4213/checkpoints/checkPoint1A1Bit/473.astar
ln -s -f -n --target-directory=/home/students/raya4213/checkpoints/checkPoint1A1Bit /home/students/raya4213/benchmarks/src/spec-cpu2006/int/473.astar/data/train/input/BigLakes1024.bin /home/students/raya4213/benchmarks/src/spec-cpu2006/int/473.astar/data/train/input/BigLakes1024.cfg /home/students/raya4213/benchmarks/src/spec-cpu2006/int/473.astar/data/train/input/rivers.bin /home/students/raya4213/benchmarks/src/spec-cpu2006/int/473.astar/data/train/input/rivers1.cfg
# setup experiment files
# run benchmark
pin -t  /home/students/raya4213/checkpoints/checkPoint1A2Bit/obj-intel64/checkpoint1A2Bit.so -o astar.out -l 10000000000 -- /home/students/raya4213/checkpoints/checkPoint1A1Bit/473.astar BigLakes1024.cfg > BigLakes1024.out 2> BigLakes.err 
# verify benchmark
# post-copy benchmark
cp /home/students/raya4213/checkpoints/checkPoint1A1Bit/astar.out /home/students/raya4213/benchmarks/src/spec-cpu2006/int/473.astar/builds/base/astar.out;
# run custom script
# clean benchmark
rm -f /home/students/raya4213/checkpoints/checkPoint1A1Bit/473.astar
rm -r -f BigLakes1024.bin BigLakes1024.cfg rivers.bin rivers1.cfg BigLakes.err BigLakes1024.err BigLakes1024.out rivers1.err rivers1.out
# clean experiment files
# log file update
echo -n "Finished: spec-cpu2006/int/473.astar input: train 0 at " >> LOG 
date >> LOG
#####################################################################
# benchmark: spec-cpu2006/int/473.astar input: train 1
#####################################################################
# log file update
echo -n "Started : spec-cpu2006/int/473.astar input: train 1 at " >> LOG 
date >> LOG
# setup
ln -s /home/students/raya4213/benchmarks/src/spec-cpu2006/int/473.astar/builds/base/473.astar /home/students/raya4213/checkpoints/checkPoint1A1Bit/473.astar
ln -s -f -n --target-directory=/home/students/raya4213/checkpoints/checkPoint1A1Bit /home/students/raya4213/benchmarks/src/spec-cpu2006/int/473.astar/data/train/input/BigLakes1024.bin /home/students/raya4213/benchmarks/src/spec-cpu2006/int/473.astar/data/train/input/BigLakes1024.cfg /home/students/raya4213/benchmarks/src/spec-cpu2006/int/473.astar/data/train/input/rivers.bin /home/students/raya4213/benchmarks/src/spec-cpu2006/int/473.astar/data/train/input/rivers1.cfg
# setup experiment files
# run benchmark
pin -t  /home/students/raya4213/checkpoints/checkPoint1A2Bit/obj-intel64/checkpoint1A2Bit.so -o astar.out -l 10000000000 -- /home/students/raya4213/checkpoints/checkPoint1A1Bit/473.astar rivers1.cfg > rivers1.out 2> rivers1.err 
# verify benchmark
# post-copy benchmark
cp /home/students/raya4213/checkpoints/checkPoint1A1Bit/astar.out /home/students/raya4213/benchmarks/src/spec-cpu2006/int/473.astar/builds/base/astar.out;
# run custom script
# clean benchmark
rm -f /home/students/raya4213/checkpoints/checkPoint1A1Bit/473.astar
rm -r -f BigLakes1024.bin BigLakes1024.cfg rivers.bin rivers1.cfg BigLakes.err BigLakes1024.err BigLakes1024.out rivers1.err rivers1.out
# clean experiment files
# log file update
echo -n "Finished: spec-cpu2006/int/473.astar input: train 1 at " >> LOG 
date >> LOG
#####################################################################
# Finishing logfile
date >> LOG
#####################################################################

