#!/bin/sh
#####################################################################
# go.sh
# Generated by bench-run.pl
# /home/students/raya4213/benchmarks/bin/bench-run.pl --bench spec-cpu2006:int:456.hmmer:train --build base --prefix pin -t  /home/students/raya4213/checkpoints/checkPoint1A2Bit/obj-intel64/checkpoint1A2Bit.so -o hmmer.out -l 10000000000 -- --copy hmmer.out --log LOG
#####################################################################

#####################################################################
# Creating logfile
date >> LOG
#####################################################################

#####################################################################
# benchmark: spec-cpu2006/int/456.hmmer input: train 0
#####################################################################
# log file update
echo -n "Started : spec-cpu2006/int/456.hmmer input: train 0 at " >> LOG 
date >> LOG
# setup
ln -s /home/students/raya4213/benchmarks/src/spec-cpu2006/int/456.hmmer/builds/base/456.hmmer /home/students/raya4213/checkpoints/checkPoint1A2Bit/456.hmmer
ln -s -f -n --target-directory=/home/students/raya4213/checkpoints/checkPoint1A2Bit /home/students/raya4213/benchmarks/src/spec-cpu2006/int/456.hmmer/data/train/input/leng100.hmm
# setup experiment files
# run benchmark
pin -t  /home/students/raya4213/checkpoints/checkPoint1A2Bit/obj-intel64/checkpoint1A2Bit.so -o hmmer.out -l 10000000000 -- /home/students/raya4213/checkpoints/checkPoint1A2Bit/456.hmmer --fixed 0 --mean 425 --num 85000 --sd 300 --seed 0 leng100.hmm > leng100.out 2> leng100.err 
# verify benchmark
# post-copy benchmark
cp /home/students/raya4213/checkpoints/checkPoint1A2Bit/hmmer.out /home/students/raya4213/benchmarks/src/spec-cpu2006/int/456.hmmer/builds/base/hmmer.out;
# run custom script
# clean benchmark
rm -f /home/students/raya4213/checkpoints/checkPoint1A2Bit/456.hmmer
rm -r -f leng100.hmm leng.hmm.new leng100.err leng100.out
# clean experiment files
# log file update
echo -n "Finished: spec-cpu2006/int/456.hmmer input: train 0 at " >> LOG 
date >> LOG
#####################################################################
# Finishing logfile
date >> LOG
#####################################################################

