#!/bin/sh
#####################################################################
# go.sh
# Generated by bench-run.pl
# /home/students/raya4213/benchmarks/bin/bench-run.pl --bench spec-cpu2006:int:471.omnetpp:train --build base --prefix pin -t  /home/students/raya4213/checkpoints/checkPoint1A2Bit/obj-intel64/checkpoint1A2Bit.so -o sjeng.out -l 10000000000 -- --copy omnetpp.out --log LOG
#####################################################################

#####################################################################
# Creating logfile
date >> LOG
#####################################################################

#####################################################################
# benchmark: spec-cpu2006/int/471.omnetpp input: train 0
#####################################################################
# log file update
echo -n "Started : spec-cpu2006/int/471.omnetpp input: train 0 at " >> LOG 
date >> LOG
# setup
ln -s /home/students/raya4213/benchmarks/src/spec-cpu2006/int/471.omnetpp/builds/base/471.omnetpp /home/students/raya4213/checkpoints/checkPoint1A2Bit/471.omnetpp
ln -s -f -n --target-directory=/home/students/raya4213/checkpoints/checkPoint1A2Bit /home/students/raya4213/benchmarks/src/spec-cpu2006/int/471.omnetpp/data/train/input/omnetpp.ini
# setup experiment files
# run benchmark
pin -t  /home/students/raya4213/checkpoints/checkPoint1A2Bit/obj-intel64/checkpoint1A2Bit.so -o sjeng.out -l 10000000000 -- /home/students/raya4213/checkpoints/checkPoint1A2Bit/471.omnetpp omnetpp.ini > omnetpp.log 2> omnetpp.err 
# verify benchmark
# post-copy benchmark
cp /home/students/raya4213/checkpoints/checkPoint1A2Bit/omnetpp.out /home/students/raya4213/benchmarks/src/spec-cpu2006/int/471.omnetpp/builds/base/omnetpp.out;
# run custom script
# clean benchmark
rm -f /home/students/raya4213/checkpoints/checkPoint1A2Bit/471.omnetpp
rm -r -f omnetpp.ini omnetpp.err omnetpp.log omnetpp.sca
# clean experiment files
# log file update
echo -n "Finished: spec-cpu2006/int/471.omnetpp input: train 0 at " >> LOG 
date >> LOG
#####################################################################
# Finishing logfile
date >> LOG
#####################################################################

